openapi: '3.0.2'
info:
  title: Pets Foundation API
  description: API encargada de gestionar la adopción de mascotas.
  version: '1.0.0'
servers:
  - url: https://fhm0e9qvti.execute-api.us-east-1.amazonaws.com/dev/
tags:
  - name: foundations
    description: Endpoint que permite crear una fundación y obtener todas las fundaciones registradas.
  - name: pets
    description: Endpoint que permite agregar una nueva mascota, obtener todas las mascotas segun la fundación, obtener solo una, actualziar sus datos, liberarla, adoptarla.

paths:
  /foundations:
    post:
      tags:
        - foundations
      summary: Registra la información de una nueva fundación.
      parameters:
        - $ref: '#/components/parameters/token'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodyFoundationPost'
      responses:
        200:
          description: (OK) Se registró la fundación correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FoundationCreatedPost'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

    get:
      tags:
        - foundations
      summary: Obtiene todas las fundaciones registradas.
      parameters:
        - $ref: '#/components/parameters/token'

      responses:
        200:
          description: (OK) Se registró la fundación correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FoundationCreatedPost'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

  /pets:
    post:
      tags:
        - pets
      summary: Agrega una nueva mascota a una fundación.
      parameters:
        - $ref: '#/components/parameters/token'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/'
      responses:
        200:
          description: (OK) Se agregó la mascota a la fundación correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FoundationCreatedPost'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

components:
  responses:
    Forbidden:
      description: (Deny) acceso al recurso denegado explicitamente.
    Unauthorized:
      description: (Unauthorized) no hay autorización para llamar el recurso.
    NotFound:
      description: (NotFound) no se encontró el recurso.
    BadRequest:
      description: (BadRequest) la data enviada se encuentra mal formateada.
    ServerError:
      description: (ServerError) Error en el servidor.

  parameters:
    token:
      name: accessToken
      in: header
      description: Token de autenticación
      schema:
        type: string
      required: true
  schemas:
    BodyFoundationPost:
      type: object
      properties:
        foundationName:
          type: string
          description: Nombre de la fundación.
        foundationAddress:
          type: string
          description: Dirección de la fundación.

    FoundationCreatedPost:
      type: object
      properties:
        response:
          type: string
          description: Mensaje de creación de fundación.
